import { CompanySettings, Customer, Product, Quotation } from './types';

export const DEFAULT_COMPANY_SETTINGS: CompanySettings = {
  id: '00000000-0000-0000-0000-000000000001',
  company_name: 'Zorame Buildtech',
  tagline: 'Building a Stronger Tomorrow | Roofing • Fabrication • PEB Buildings • Engineering Works',
  phone: '+91 94431 52678 / +91 98424 52678',
  email: 'zoramebuildtech@gmail.com',
  address: 'No. 12, Sangliandapuram Main Road, Near Palakarai, Tiruchirappalli (Trichy), Tamil Nadu 620001',
  gst_tax_id: '33AAGFS1234F1Z9',
  logo_url: '/logo.png',
  quote_prefix: 'ZB-',
  default_validity_days: 15,
  default_steel_price_per_kg: 78.00,
  default_terms: `1. Prices are inclusive of applicable GST unless stated otherwise.
2. Delivery within city limits and nearby districts within 2-4 working days upon order confirmation.
3. Loading and transport freight charges extra at actuals unless explicitly quoted.
4. Material cutting and custom profile orders cannot be cancelled once processing has commenced.
5. Quotation is valid for the specified period due to raw material and steel market price movements.`,
  bank_details: `Bank Name: State Bank of India
Account Name: Zorame Buildtech
Account No: 38901234567
IFSC Code: SBIN0001234
Branch: Trichy Main`,
};

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'FRP (Fiber Reinforced Plastic) Corrugated Sheet 2mm (Natural White)',
    category: 'Roofing Sheet',
    unit: 'meter',
    unit_price: 68.00,
    tax_rate: 18.00,
    description: 'High strength UV resistant translucent daylight FRP roofing sheet',
    is_active: true,
  },
  {
    id: 'prod-2',
    name: 'Polycarbonate Multiwall Embossed Sheet 2mm (Clear / Opal)',
    category: 'Roofing Sheet',
    unit: 'meter',
    unit_price: 95.00,
    tax_rate: 18.00,
    description: 'Unbreakable daylight skylight roofing sheet with UV protective coating',
    is_active: true,
  },
  {
    id: 'prod-3',
    name: 'Color Coated Galvalume Trapezoidal Sheet 0.47mm (Castle Red / Mist Green)',
    category: 'Roofing Sheet',
    unit: 'meter',
    unit_price: 58.50,
    tax_rate: 18.00,
    description: 'AZ150 high tensile 550 MPA Galvalume profiled roofing sheet',
    is_active: true,
  },
  {
    id: 'prod-4',
    name: 'Self Drilling Screws with EPDM Washer 12 x 55mm (Pack of 100)',
    category: 'Screw',
    unit: 'box',
    unit_price: 450.00,
    tax_rate: 18.00,
    description: 'Hex head with ruspert anti-corrosion coating & bonded EPDM washer',
    is_active: true,
  },
  {
    id: 'prod-5',
    name: 'Self Drilling Stitching Screws 12 x 25mm (Pack of 100)',
    category: 'Screw',
    unit: 'box',
    unit_price: 380.00,
    tax_rate: 18.00,
    description: 'Side lap stitching screws with neoprene washer',
    is_active: true,
  },
  {
    id: 'prod-6',
    name: 'MS Rectangular Hollow Section Pipe 50x25x2mm (18ft length)',
    category: 'Pipe',
    unit: 'pcs',
    unit_price: 1250.00,
    tax_rate: 18.00,
    description: 'Structural purlin support mild steel pipe',
    is_active: true,
  },
  {
    id: 'prod-7',
    name: 'GI Round Pipe 2 Inch Class B (20ft length)',
    category: 'Pipe',
    unit: 'pcs',
    unit_price: 1850.00,
    tax_rate: 18.00,
    description: 'Heavy grade galvanized iron drainage and structure pipe',
    is_active: true,
  },
  {
    id: 'prod-8',
    name: 'FRP Ridge Cap (Matching Sheet Profile & Color, 8ft)',
    category: 'Accessory',
    unit: 'pcs',
    unit_price: 520.00,
    tax_rate: 18.00,
    description: 'Molded fiber apex ridge cap for weather-tight crown sealing',
    is_active: true,
  },
  {
    id: 'prod-9',
    name: 'Rain Water Gutter 0.50mm (8ft Length)',
    category: 'Accessory',
    unit: 'pcs',
    unit_price: 620.00,
    tax_rate: 18.00,
    description: 'High capacity eaves water drainage gutter',
    is_active: true,
  },
  {
    id: 'prod-10',
    name: 'Corner Flashing / Gable Flashing 0.47mm (8ft)',
    category: 'Accessory',
    unit: 'pcs',
    unit_price: 350.00,
    tax_rate: 18.00,
    description: 'Side barge and wind-proof flashing trims',
    is_active: true,
  },
  {
    id: 'prod-11',
    name: 'Silicon Sealant Weatherproof Cartridge 300ml',
    category: 'Accessory',
    unit: 'pcs',
    unit_price: 240.00,
    tax_rate: 18.00,
    description: 'Neutral cure silicone for leak-proof joints & lap sealing',
    is_active: true,
  },
  {
    id: 'prod-12',
    name: 'Fiber & Metal Sheet Installation & Fixing Labor',
    category: 'Labor',
    unit: 'sqft',
    unit_price: 15.00,
    tax_rate: 18.00,
    description: 'Professional on-site hoisting, alignment, drilling, and fixing',
    is_active: true,
  },
  {
    id: 'prod-13',
    name: 'Roof Truss Fabrication & Purlin Welding Charges',
    category: 'Labor',
    unit: 'kg',
    unit_price: 24.00,
    tax_rate: 18.00,
    description: 'Cutting, assembly, and welding of steel trusses and purlins',
    is_active: true,
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Kaveri Constructions & Fabricators',
    phone: '+91 94432 10987',
    email: 'kaveri.fabricators@gmail.com',
    address: 'No. 45, Thillai Nagar 11th Cross, Tiruchirappalli, Tamil Nadu',
    site_location: 'Industrial Warehouse Shed, Thuvakudi SIDCO, Trichy',
    notes: 'Regular client for FRP daylight panels and Galvalume roofing',
  },
  {
    id: 'cust-2',
    name: 'Vasanth Polyhouse & Farm Projects',
    phone: '+91 98424 77665',
    email: 'vasanthfarms.trichy@yahoo.com',
    address: 'Manapparai Road, Tiruchirappalli',
    site_location: 'Greenhouse & Shed Project, Viralimalai',
    notes: 'Needs quotation with UV coated transparent fiber sheets',
  },
  {
    id: 'cust-3',
    name: 'Sri Ranganathar Rice Mill & Warehouse',
    phone: '+91 97880 33441',
    email: 'sriranganathar.ricemill@outlook.com',
    address: 'Srirangam bypass road, Tiruchirappalli',
    site_location: 'Commercial Godown Roof Replacement, Palakarai, Trichy',
    notes: 'Requires quick delivery within 2 days',
  },
];

export const INITIAL_QUOTATIONS: Quotation[] = [];
